Debugging deploy to server

diff --git a/.github/workflows/deploy-to-server.yml b/.github/workflows/deploy-to-server.yml
--- a/.github/workflows/deploy-to-server.yml
+++ b/.github/workflows/deploy-to-server.yml
@@ -12,5 +12,16 @@ jobs:
 
       - name: Make API request using curl
         run: |
-          curl --location --request POST 'loonsw.sci.utah.edu:5421/deploy' \
-          --header 'Authorization: ${{secrets.DEPLOYMENT_AUTH_TOKEN}}'
+          curl --location --request POST 'https://loonsw.sci.utah.edu:5421/deploy' \
+            --header 'Authorization: ${{secrets.DEPLOYMENT_AUTH_TOKEN}}' \
+            --max-time 10 \
+            --fail \
+            --show-error \
+            --silent
+
+      - name: Check for status code
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to reach the server or no response. Exiting..."
+            exit 1
+          fi
